name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger this workflow when changes are pushed to the main branch
    paths:
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - '**.gif'
      - '**.webp'

jobs:
  optimize-images:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compress Images
        id: compress-images
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          compressOnly: true  # This ensures images are compressed but not committed back to PR
          # Optional compression settings
          jpegQuality: 80
          pngQuality: 80
          webpQuality: 80
          # Ensure GIF animations are preserved
          gifski: false

      - name: Commit compressed images
        if: steps.compress-images.outputs.markdown != ''
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Optimize images [skip ci]"
          git push

  deploy:
    needs: optimize-images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # This will get the latest code with optimized images

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20  # Use Node.js version 20

      - name: Install dependencies
        run: npm install  # Install the dependencies

      - name: Build and export site
        run: |
          npm run build
          npm run export  # Export the site to static files

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4  # Action to deploy to GitHub Pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Automatically access the GitHub repository
          publish_dir: ./out  # Directory to push to gh-pages
          publish_branch: gh-pages  # Push to gh-pages branch
