name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger this workflow when changes are pushed to the main branch

jobs:
  optimize-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Optimize images
        uses: imgbot/action@v1
        with:
          # Optional parameters
          schedule: "daily" # Options: daily, weekly, monthly
          ignoredFiles: "*.svg" # Ignore SVG files if needed
          aggressiveCompression: "true" # Set to true for maximum compression
          
      - name: Commit optimized images
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add -A
          git commit -m "Optimize images" || echo "No changes to commit"
          git push

  deploy:
    needs: optimize-images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Install dependencies
        run: npm install
        
      - name: Build and export site
        run: |
          npm run build
          npm run export
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          publish_branch: gh-pages
